import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { SpeedInsights } from "@vercel/speed-insights/next"
import { GoogleTagManager, GoogleAnalytics } from '@next/third-parties/google';
import { Analytics } from "@vercel/analytics/next"

import { routing } from '@/shared/i18n/routing';
import { ThemeProvider } from "@/shared/providers";
import { ErrorBoundary } from "@/shared/ui";
import { GoogleAdSense } from "@/shared/lib/analytics";
import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";

import { Outfit, Inter } from "next/font/google";

import "../globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'),
  title: {
    default: "VXD's web",
    template: "%s | VXD's web",
  },
  description: "Generated by Vision eXperience Developer",
  keywords: ["VXD", "Blog", "vision experience developer", "React", "TypeScript", "Google", "AI", "Frontend", "Backend", "Web Development", "Mobile Development", "Vision", "Experience", "Developer", "Software Engineer", "Software Developer", "Thinking", "Coding", "Programming", "Development"],
  openGraph: {
    title: "VXD's web",
    description: "Generated by Vision eXperience Developer",
    url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
    siteName: "VXD's web",
    locale: "en_US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  other: {
    "google-adsense-account": process.env.GOOGLE_ADSENSE_ACCOUNT ?? "",
  },
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <GoogleTagManager gtmId={process.env.GTM_ID ?? ""} />
      <body
        className={`${outfit.variable} ${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        <GoogleAnalytics gaId={process.env.GA_ID ?? ""} />
        <GoogleAdSense pId={process.env.GOOGLE_ADSENSE_ID ?? ""} />
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ErrorBoundary>
              <Header />
              {children}
              <Footer />
            </ErrorBoundary>
          </ThemeProvider>
        </NextIntlClientProvider>
        <SpeedInsights/>
        <Analytics />
      </body>
    </html>
  );
}
